edu:
  fpt:
    capstone:
      vms:
        permitAll: /v3/api-docs/**,/swagger-ui/**,/actuator/**,/favicon.ico,/error,/api/v1/user/filter-available-users,/api/v1/card,/api/v1/card/**
        oauth2:
          provider: keycloak
          keycloak:
            realm: vms
            issuer-uri: https://idm-vms.azurewebsites.net/realms/${edu.fpt.capstone.vms.oauth2.keycloak.realm}
            jwk-set-uri: ${edu.fpt.capstone.vms.oauth2.keycloak.issuer-uri}/protocol/openid-connect/certs
            client-id: vms-api
            principal-attribute: preferred_username
            credentials-secret: uq9MroK6qI2gs77wEIKG6ZroKCnzgZMt
            admin-username: admin
            admin-password: admin
            ignore-default-roles: default-roles-${edu.fpt.capstone.vms.oauth2.keycloak.realm},offline_access,uma_authorization

management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      cors:
        allowed-origins: http://localhost:3000
      exposure:
        include: health,info,metrics,prometheus,bindings,beans,env,loggers,streamsbindings
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8000

spring:
  application:
    name: vms-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://vms-db.postgres.database.azure.com:5432/vms-db
    username: vms
    password: Password123
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    generate-ddl: true
    properties:
      javax:
        persistence:
          create-database-schemas: true
  jackson:
    default-property-inclusion: NON_NULL


  #  liquibase:
  #    change-log: classpath:db/changelog-master.yml
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${edu.fpt.capstone.vms.oauth2.keycloak.issuer-uri}
          jwk-set-uri: ${edu.fpt.capstone.vms.oauth2.keycloak.jwk-set-uri}
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB


  main:
    allow-bean-definition-overriding: true
  cache:
    disabled: true
  swagger-ui:
    use-root-path: true
  api-docs:
    enabled: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    root: info
    web: info
  file:
    name: ./logs/info.log

azure:
  account:
    name: vmscloudstorage
    key: LxYDFSlRehhfoRy878Ej58JlFUsaB/BYGo+TSo8LoeRqkkS498OJLvcEt71j9yTQmiYgVw6PU7p1+AStq2a/ew==
  container:
    name: vms-file-storage

schedule:
  cleaningImage:
    time: 0 0 22 * * *
