version: '3.8'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.2
    command: [ 'start-dev --import-realm' ]
    volumes:
      - ./volume/keycloak/providers:/opt/keycloak/providers
    networks:
      - vms
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://vms-db.postgres.database.azure.com:5432/vms-keycloak-db?sslmode=verify-ca&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
      - KC_DB_USERNAME=vms
      - KC_DB_PASSWORD=Password123
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HTTP_PORT=9080
      - KC_HTTPS_PORT=9443
      - KC_HEALTH_ENABLED=true
    ports:
      - "9080:9080"
      - "9443:9443"



networks:
  vms:
    name: vms-network
    driver: bridge
