version: '3.8'
name: server
services:
  sonar:
    container_name: sonarqube
    image: sonarqube:10.1.0-community
    environment:
      - SONAR_FORCEAUTHENTICATION=false
    ports:
      - "9000:9000"
    networks:
      - vms

networks:
  vms:
    name: vms-network
    driver: bridge
